sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -f Dockerfile -t $DOCKER_USER/travis-ci-build-stages-demo .
  - docker images  
  - docker ps -a

after_success:
  - docker --version 
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO= $DOCKER_USER/travis-ci-build-stages-demo
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO